-- Inserir dados de exemplo na tabela trend_rush
INSERT INTO trend_rush (
  title,
  description,
  audio_url,
  image_url,
  status,
  platform,
  artist,
  tags,
  is_featured,
  view_count,
  priority
) VALUES 
(
  'Trilha Sonora Para Story de Viagem',
  'Áudio perfeito para stories de viagens ou momentos especiais ao ar livre.',
  'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Concentration.mp3',
  'https://images.unsplash.com/photo-1503220317375-aaad61436b1b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  'published',
  'instagram',
  'Digital Fy',
  ARRAY['viagem', 'natureza', 'stories'],
  true,
  12500,
  1
),
(
  'Beat Para Transição de Vídeo TikTok',
  'Beat rítmico perfeito para transições de vídeo no TikTok.',
  'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Vibe%20Mountain.mp3',
  'https://images.unsplash.com/photo-1611162616475-46b635cb6868?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  'published',
  'tiktok',
  'Producer X',
  ARRAY['beat', 'transição', 'viral'],
  false,
  8900,
  2
),
(
  'Som Trending para Reels de Moda',
  'Áudio em alta para Reels de moda e tendências de estilo.',
  'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Harmful%20or%20Fatal.mp3',
  'https://images.unsplash.com/photo-1483985988355-763728e1935b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  'published',
  'both',
  'Style Sounds',
  ARRAY['moda', 'estilo', 'reels'],
  true,
  15300,
  3
),
(
  'Efeito Sonoro Para Revelação de Produto',
  'Efeito dramático para vídeos de unboxing ou revelação de produtos.',
  'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Evening%20of%20Chaos.mp3',
  'https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  'published',
  'both',
  'Marketing Audio',
  ARRAY['produto', 'unboxing', 'efeito'],
  false,
  7600,
  4
),
(
  'Base Musical Para Tutoriais',
  'Base musical suave ideal para vídeos de tutorial e DIY.',
  'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Almost%20in%20F%20-%20Tranquillity.mp3',
  'https://images.unsplash.com/photo-1544819667-9bfc1de23d4e?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  'published',
  'instagram',
  'Produções Criativas',
  ARRAY['tutorial', 'diy', 'calmo'],
  false,
  6300,
  5
),
(
  'Som Viral Para Desafio TikTok',
  'Som que está viralizando em desafios no TikTok.',
  'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Hustle.mp3',
  'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  'published',
  'tiktok',
  'Viral Tracks',
  ARRAY['desafio', 'viral', 'tendência'],
  true,
  21000,
  6
),
(
  'Jingle Para Anúncio de Loja',
  'Jingle comercial perfeito para anúncios de lojas e promoções.',
  'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Spy%20Glass.mp3',
  'https://images.unsplash.com/photo-1472851294608-062f824d29cc?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  'published',
  'both',
  'Commercial Audio',
  ARRAY['anúncio', 'loja', 'comercial'],
  false,
  5500,
  7
),
(
  'Música Para Conteúdo Motivacional',
  'Trilha inspiradora para vídeos motivacionais e de desenvolvimento pessoal.',
  'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Monkeys%20Spinning%20Monkeys.mp3',
  'https://images.unsplash.com/photo-1533228100845-08145b01de14?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  'published',
  'instagram',
  'Inspire Audio',
  ARRAY['motivacional', 'inspirador', 'desenvolvimento'],
  false,
  9300,
  8
),
(
  'Som De Fundo Para Review de Produto',
  'Áudio neutro e profissional para reviews e análises de produtos.',
  'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Space%20Jazz.mp3',
  'https://images.unsplash.com/photo-1542291026-7eec264c27ff?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  'published',
  'both',
  'Review Masters',
  ARRAY['review', 'análise', 'produto'],
  false,
  4800,
  9
),
(
  'Trilha Para Time-lapse',
  'Música rítmica ideal para vídeos em time-lapse e hyperlapse.',
  'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Backbay%20Lounge.mp3',
  'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60',
  'published',
  'both',
  'Visual Audio',
  ARRAY['timelapse', 'hyperlapse', 'cinematografia'],
  true,
  11200,
  10
); 